import {
  RentalProperty,
  FlipProject,
  OpportunityDeal,
  FundingSource,
  LocalSupplier,
  TaskItem,
  InvestorProfile,
} from '@/types';
import { computeAcquisitionCosts, calculateSection13sex } from '@/lib/calculations/sarsTax';
import {
  calculateDealMetrics,
  computeBuiltInEquity,
  computeAmenityScore,
} from '@/lib/calculations/propertyMetrics';

export const INITIAL_RENTALS: RentalProperty[] = [
  {
    id: 'rental-1',
    title: 'Sandhurst Executive Suite',
    address: '35 Fredman Drive, Sandton',
    city: 'Johannesburg',
    propertyType: 'Sectional Title Apartment',
    marketValueZAR: 2_450_000,
    purchasePriceZAR: 2_100_000,
    purchaseDate: '2023-03-15',
    outstandingBondBalanceZAR: 1_280_000,
    bondInterestRatePercent: 11.75,
    monthlyBondPaymentZAR: 13_850,
    tenantName: 'Dr. Thabo Mokoena',
    tenantPhone: '+27 82 456 7890',
    tenantEmail: 'thabo.mokoena@medclinic.co.za',
    leaseStartDate: '2023-04-01',
    leaseEndDate: '2027-03-31',
    depositHeldZAR: 37_000,
    annualEscalationPercent: 7.0,
    managementType: 'Agency',
    agencyName: 'Pam Golding Sandton',
    agencyCommissionPercent: 8.0,
    agencyVatApplicable: false,
    agencyContact: '+27 82 555 1234',
    monthlyGrossRentZAR: 18_500,
    monthlyLeviesZAR: 2_850,
    monthlyRatesTaxesZAR: 1_450,
    monthlyAgentFeeZAR: 1_480,
    monthlyMaintenanceReserveZAR: 800,
    status: 'Occupied',
    maintenanceHistory: [
      {
        id: 'maint-1',
        dateLogged: '2026-07-10',
        issueDescription: 'Geyser pressure valve replacement',
        category: 'Plumbing',
        contractorName: 'Sandton Rapid Plumbing',
        costZAR: 2_850,
        status: 'Resolved',
        invoiceRef: 'INV-8821',
      },
      {
        id: 'maint-2',
        dateLogged: '2026-08-22',
        issueDescription: 'Inverter system routine battery check',
        category: 'Electrical',
        contractorName: 'VoltTech Spark Services',
        costZAR: 1_200,
        status: 'Resolved',
        invoiceRef: 'INV-9014',
      },
    ],
    cocChecklist: {
      electrical: { type: 'Electrical', status: 'Certified / Valid', issueDate: '2026-03-20', certificateNumber: 'EC-99214' },
      gas: { type: 'Gas', status: 'Not Applicable' },
      electricFence: { type: 'Electric Fence', status: 'Not Applicable' },
      plumbing: { type: 'Plumbing (Cape Town)', status: 'Not Applicable' },
      beetle: { type: 'Beetle', status: 'Not Applicable' },
    },
    driveVault: {
      masterFolderUrl: 'https://drive.google.com/drive/folders/sandhurst-suite-demo',
      otpDocumentUrl: 'https://drive.google.com/file/d/otp-sandhurst-signed/view',
      ratesBillUrl: 'https://drive.google.com/file/d/rates-jhb-sandhurst/view',
      titleDeedUrl: 'https://drive.google.com/file/d/titledeed-sandhurst/view',
    },
  },
  {
    id: 'rental-2',
    title: 'Umhlanga Ridge Coastal Vista',
    address: '14 The Boulevard, Umhlanga Ridge',
    city: 'Durban',
    propertyType: 'Sectional Title Apartment',
    marketValueZAR: 1_850_000,
    purchasePriceZAR: 1_650_000,
    purchaseDate: '2023-09-01',
    outstandingBondBalanceZAR: 940_000,
    bondInterestRatePercent: 11.5,
    monthlyBondPaymentZAR: 10_020,
    tenantName: 'Priya Pillay',
    tenantPhone: '+27 83 912 3456',
    tenantEmail: 'priya.pillay@oceanlogistics.co.za',
    leaseStartDate: '2023-10-01',
    leaseEndDate: '2026-11-30',
    depositHeldZAR: 30_400,
    annualEscalationPercent: 6.5,
    managementType: 'Self-Managed',
    agencyCommissionPercent: 0,
    agencyVatApplicable: false,
    agencyContact: '',
    monthlyGrossRentZAR: 15_200,
    monthlyLeviesZAR: 2_150,
    monthlyRatesTaxesZAR: 1_180,
    monthlyAgentFeeZAR: 0,
    monthlyMaintenanceReserveZAR: 600,
    status: 'Occupied',
    maintenanceHistory: [
      {
        id: 'maint-3',
        dateLogged: '2026-08-14',
        issueDescription: 'Balcony sliding door roller track repair',
        category: 'General Wear',
        contractorName: 'KZN Aluminium Works',
        costZAR: 1_650,
        status: 'Resolved',
        invoiceRef: 'KZN-4412',
      },
    ],
  },
  {
    id: 'rental-3',
    title: 'Green Point Urban Loft',
    address: '88 Somerset Road, Green Point',
    city: 'Cape Town',
    propertyType: 'Sectional Title Apartment',
    marketValueZAR: 3_200_000,
    purchasePriceZAR: 2_750_000,
    purchaseDate: '2022-11-10',
    outstandingBondBalanceZAR: 1_550_000,
    bondInterestRatePercent: 11.25,
    monthlyBondPaymentZAR: 16_240,
    tenantName: 'Matthew van der Merwe',
    tenantPhone: '+27 71 889 0012',
    tenantEmail: 'matthew.vdm@capetech.io',
    leaseStartDate: '2024-01-01',
    leaseEndDate: '2026-12-31',
    depositHeldZAR: 49_000,
    annualEscalationPercent: 8.0,
    managementType: 'Agency',
    agencyName: 'RE/MAX Living Cape Town',
    agencyCommissionPercent: 8.0,
    agencyVatApplicable: false,
    agencyContact: '+27 71 889 0012',
    monthlyGrossRentZAR: 24_500,
    monthlyLeviesZAR: 3_200,
    monthlyRatesTaxesZAR: 1_950,
    monthlyAgentFeeZAR: 1_960,
    monthlyMaintenanceReserveZAR: 1_000,
    status: 'Occupied',
    maintenanceHistory: [],
  },
];

export const INITIAL_FLIPS: FlipProject[] = [
  {
    id: 'flip-1',
    title: 'Kloof Street Heritage Redesign',
    address: '74 Kloof Street, Gardens',
    city: 'Cape Town',
    purchaseDate: '2026-03-01',
    purchasePriceZAR: 3_800_000,
    acquisitionCostsZAR: 315_000,
    baselineRenovationBudgetZAR: 750_000,
    targetExitPriceZAR: 5_650_000,
    targetCompletionDate: '2026-11-15',
    currentPhase: 'Finishes & Tiling',
    linkedFundingIds: ['fund-1'],
    status: 'Active',
    notes: 'Restoring historic Victorian facade while introducing open-plan modern Scandinavian interior.',
    boq: [
      {
        id: 'boq-1',
        category: 'Demolition & Prep',
        itemDescription: 'Removal of partition walls & asbestos roof shed demolition',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 45_000,
        baselineTotalZAR: 45_000,
        actualCostZAR: 42_500,
        varianceZAR: -2_500,
        supplierOrContractor: 'Cape Strip & Demolition Co.',
        status: 'Completed',
        invoiceRef: 'CSD-019',
      },
      {
        id: 'boq-2',
        category: 'Electrical & Lighting',
        itemDescription: 'Full rewiring, recessed LED downlights, and 8kVA Sunsynk Solar Inverter',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 140_000,
        baselineTotalZAR: 140_000,
        actualCostZAR: 148_000,
        varianceZAR: 8_000,
        supplierOrContractor: 'Master Electricians CT (Wireman CoC)',
        status: 'In Progress',
        invoiceRef: 'MEC-441',
      },
      {
        id: 'boq-3',
        category: 'Plumbing & Wet Works',
        itemDescription: 'Re-pipe copper to PEX, install concealed cisterns & freestanding bath',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 95_000,
        baselineTotalZAR: 95_000,
        actualCostZAR: 91_200,
        varianceZAR: -3_800,
        supplierOrContractor: 'Plumblink Foreshore / Cape Coastal Plumbing',
        status: 'In Progress',
        invoiceRef: 'CCP-992',
      },
      {
        id: 'boq-4',
        category: 'Kitchen & Cabinetry',
        itemDescription: 'Custom matte charcoal soft-close joinery & engineered quartz countertops',
        unit: 'linear m',
        quantity: 12,
        baselineUnitCostZAR: 16_000,
        baselineTotalZAR: 192_000,
        actualCostZAR: 188_000,
        varianceZAR: -4_000,
        supplierOrContractor: 'Elite Joinery Paarden Eiland',
        status: 'In Progress',
      },
      {
        id: 'boq-5',
        category: 'Flooring & Tiling',
        itemDescription: 'Herringbone vinyl luxury planks & 1200x600 porcelain bathroom tiles',
        unit: 'm2',
        quantity: 140,
        baselineUnitCostZAR: 850,
        baselineTotalZAR: 119_000,
        actualCostZAR: 124_000,
        varianceZAR: 5_000,
        supplierOrContractor: 'Tile Africa Northgate / Builders Warehouse',
        status: 'In Progress',
      },
      {
        id: 'boq-6',
        category: 'Painting & Finishes',
        itemDescription: 'Plascon Double Velvet interior & Micatex exterior weather shield',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 75_000,
        baselineTotalZAR: 75_000,
        actualCostZAR: 70_000,
        varianceZAR: -5_000,
        supplierOrContractor: 'ProCoat Painters Cape',
        status: 'Quoted',
      },
    ],
    cocChecklist: {
      electrical: { type: 'Electrical', status: 'Pending Inspection' },
      gas: { type: 'Gas', status: 'Pending Inspection' },
      electricFence: { type: 'Electric Fence', status: 'Not Applicable' },
      plumbing: { type: 'Plumbing (Cape Town)', status: 'Pending Inspection' },
      beetle: { type: 'Beetle', status: 'Certified / Valid', issueDate: '2026-08-10', certificateNumber: 'BC-99104' },
    },
    driveVault: {
      masterFolderUrl: 'https://drive.google.com/drive/folders/kloof-heritage-flip-demo',
      otpDocumentUrl: 'https://drive.google.com/file/d/kloof-otp-signed/view',
      ratesBillUrl: 'https://drive.google.com/file/d/cityofcapetown-rates-kloof/view',
      titleDeedUrl: 'https://drive.google.com/file/d/kloof-approved-plans-sg-diagram/view',
    },
  },
  {
    id: 'flip-2',
    title: 'Waterkloof Diplomatic Fixer',
    address: '112 Crown Avenue, Waterkloof',
    city: 'Pretoria',
    purchaseDate: '2026-05-15',
    purchasePriceZAR: 2_100_000,
    acquisitionCostsZAR: 148_000,
    baselineRenovationBudgetZAR: 480_000,
    targetExitPriceZAR: 3_350_000,
    targetCompletionDate: '2026-12-20',
    currentPhase: 'First Fix (Plumbing/Elec)',
    linkedFundingIds: ['fund-2'],
    status: 'Active',
    notes: 'Distressed purchase from bank repo. Converting outdated 3-bed into 4-bed modern family residence with entertainment patio.',
    boq: [
      {
        id: 'boq-7',
        category: 'Demolition & Prep',
        itemDescription: 'Site clearance and pool re-marbelite prep',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 35_000,
        baselineTotalZAR: 35_000,
        actualCostZAR: 35_000,
        varianceZAR: 0,
        supplierOrContractor: 'Pretoria Earthworks',
        status: 'Completed',
      },
      {
        id: 'boq-8',
        category: 'Roofing & Structural',
        itemDescription: 'Replace broken concrete roof tiles and waterproof flashing',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 65_000,
        baselineTotalZAR: 65_000,
        actualCostZAR: 68_500,
        varianceZAR: 3_500,
        supplierOrContractor: 'Chamberlains Menlyn Hardware',
        status: 'Completed',
      },
      {
        id: 'boq-9',
        category: 'Electrical & Lighting',
        itemDescription: 'New DB board, perimeter solar security floodlights, smart switches',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 85_000,
        baselineTotalZAR: 85_000,
        actualCostZAR: 78_000,
        varianceZAR: -7_000,
        supplierOrContractor: 'Jakobs Electrical Services',
        status: 'In Progress',
      },
      {
        id: 'boq-10',
        category: 'Kitchen & Cabinetry',
        itemDescription: 'High-gloss white shaker cabinets & Caesarstone countertops',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 135_000,
        baselineTotalZAR: 135_000,
        actualCostZAR: 135_000,
        varianceZAR: 0,
        supplierOrContractor: 'Leroy Merlin Fourways / Builders',
        status: 'Quoted',
      },
    ],
  },
];

export const INITIAL_FUNDING: FundingSource[] = [
  {
    id: 'fund-1',
    lenderName: 'Johan Meyer',
    entityOrContact: 'Meyer Family Trust',
    emailPhone: 'johan@meyerholdings.co.za / +27 82 555 1234',
    fundingType: 'Private Lender',
    capitalAmountZAR: 1_500_000,
    disbursementDate: '2026-03-01',
    maturityDate: '2026-11-30',
    returnTermsType: 'Fixed Interest',
    returnRatePercent: 14.0, // 14% p.a.
    paymentSchedule: 'Monthly Interest',
    linkedDealId: 'flip-1',
    linkedDealName: 'Kloof Street Heritage Redesign',
    totalRepaidZAR: 105_000, // Monthly payments made
    status: 'Active',
    notes: 'First registered second-mortgage bond over Kloof Street. Monthly coupon R17,500.',
  },
  {
    id: 'fund-2',
    lenderName: 'Protea Property Syndicate',
    entityOrContact: 'Kobus van Zyl (MD)',
    emailPhone: 'kobus@proteasyndicate.co.za / +27 83 777 9876',
    fundingType: 'Proposal-backed',
    capitalAmountZAR: 800_000,
    disbursementDate: '2026-05-15',
    maturityDate: '2026-12-31',
    returnTermsType: 'Equity Profit Split',
    returnRatePercent: 25.0, // 25% share of net flip profit
    paymentSchedule: 'At Exit (Maturity)',
    linkedDealId: 'flip-2',
    linkedDealName: 'Waterkloof Diplomatic Fixer',
    totalRepaidZAR: 0,
    status: 'Active',
    notes: 'JV syndicate backing the Waterkloof acquisition & BOQ tranche.',
  },
  {
    id: 'fund-3',
    lenderName: 'Oom Piet Bezuidenhout',
    entityOrContact: 'Personal Account',
    emailPhone: '+27 82 333 4455',
    fundingType: 'Ad-hoc Friends & Family',
    capitalAmountZAR: 450_000,
    disbursementDate: '2026-04-01',
    maturityDate: '2027-04-01',
    returnTermsType: 'Fixed Interest',
    returnRatePercent: 11.5,
    paymentSchedule: 'At Exit (Maturity)',
    linkedDealId: undefined,
    linkedDealName: 'Liquid Operational Reserve',
    totalRepaidZAR: 0,
    status: 'Active',
    notes: 'Working capital cushion for rapid auction deposits and materials cash discounts.',
  },
];

export const INITIAL_SUPPLIERS: LocalSupplier[] = [
  {
    id: 'sup-1',
    name: 'Builders Warehouse Sandton',
    category: 'General Building Merchant',
    branchLocation: 'Rivonia Rd, Sandton, JHB',
    contactPerson: 'David Khumalo',
    phone: '+27 11 897 5000',
    email: 'sandton@builders.co.za',
    accountNumber: 'BW-90234',
    discountTerms: '7.5% Trade Cash & Carry / 30 Day Net',
    rating: 5,
  },
  {
    id: 'sup-2',
    name: 'Chamberlains Hardware Menlyn',
    category: 'Hardware & Timber',
    branchLocation: 'Atterbury Rd, Menlyn, Pretoria',
    contactPerson: 'Francois du Plessis',
    phone: '+27 12 348 1234',
    email: 'menlyn@chamberlains.co.za',
    accountNumber: 'CH-4512',
    discountTerms: '5% Contractor Discount',
    rating: 5,
  },
  {
    id: 'sup-3',
    name: 'Plumblink Foreshore',
    category: 'Plumbing Supplies',
    branchLocation: 'Marine Drive, Paarden Eiland, Cape Town',
    contactPerson: 'Wayne Peterson',
    phone: '+27 21 511 7788',
    email: 'capetown@plumblink.co.za',
    accountNumber: 'PL-7789',
    discountTerms: '10% on Sanitaryware & Geysers',
    rating: 4,
  },
  {
    id: 'sup-4',
    name: 'Tile Africa Centurion',
    category: 'Tiles & Sanitary',
    branchLocation: 'Old JHB Road, Centurion',
    contactPerson: 'Nomsa Sithole',
    phone: '+27 12 653 4400',
    email: 'centurion@tileafrica.co.za',
    accountNumber: 'TA-1120',
    discountTerms: '8% Bulk Porcelain Pricing',
    rating: 4,
  },
  {
    id: 'sup-5',
    name: 'Master Electricians SA',
    category: 'Specialist Contractor',
    branchLocation: 'Cape Town & Boland',
    contactPerson: 'Liam Jacobs (Wireman Licence 44021)',
    phone: '+27 82 990 1122',
    email: 'liam@masterspark.co.za',
    hasCoC: true,
    rating: 5,
  },
  {
    id: 'sup-6',
    name: 'Leroy Merlin Fourways',
    category: 'General Building Merchant',
    branchLocation: 'Witkoppen Rd, Fourways, JHB',
    phone: '+27 10 493 8000',
    email: 'fourways@leroymerlin.co.za',
    discountTerms: 'Pro Loyalty Rebate Scheme',
    rating: 4,
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'task-1',
    title: 'Lodge transfer documents with Cape Town Deeds Office',
    description: 'Ensure conveyancer STBB Cape Town submits deeds lodgement for Kloof Street property.',
    dueDate: '2026-09-22',
    priority: 'Urgent',
    status: 'In Progress',
    linkedEntity: {
      type: 'flip',
      id: 'flip-1',
      name: 'Kloof Street Heritage Redesign',
    },
    createdAt: '2026-09-10',
  },
  {
    id: 'task-2',
    title: 'Process monthly interest coupon payout to Johan Meyer',
    description: 'Pay R17,500 coupon (14% p.a. on R1.5M) for Kloof Street private loan facility.',
    dueDate: '2026-09-30',
    priority: 'High',
    status: 'Pending',
    linkedEntity: {
      type: 'funding',
      id: 'fund-1',
      name: 'Johan Meyer (Private Lender)',
    },
    createdAt: '2026-09-12',
  },
  {
    id: 'task-3',
    title: 'Inspect waterproofing certificate at Sandhurst Towers',
    description: 'Body corporate requires updated plumber certificate following pressure valve repair.',
    dueDate: '2026-09-25',
    priority: 'High',
    status: 'Pending',
    linkedEntity: {
      type: 'rental',
      id: 'rental-1',
      name: 'Sandhurst Executive Suite',
    },
    createdAt: '2026-09-14',
  },
  {
    id: 'task-4',
    title: 'Draft 60-day lease renewal notice for Priya Pillay',
    description: 'Umhlanga lease expires 30 Nov 2026. Propose standard 6.5% escalation (R16,188/mo).',
    dueDate: '2026-10-01',
    priority: 'Medium',
    status: 'Pending',
    linkedEntity: {
      type: 'rental',
      id: 'rental-2',
      name: 'Umhlanga Ridge Coastal Vista',
    },
    createdAt: '2026-09-15',
  },
  {
    id: 'task-5',
    title: 'Attend Sheriff Auction in Randburg for distressed Parkhurst asset',
    description: 'Registration fee R50k refundable deposit. Max bid threshold set at R1.85M.',
    dueDate: '2026-10-05',
    priority: 'High',
    status: 'Pending',
    linkedEntity: {
      type: 'opportunity',
      id: 'opp-1',
      name: 'Parkhurst Distressed Sheriff Auction',
    },
    createdAt: '2026-09-16',
  },
];

// Helper to create pre-calculated initial opportunities
function createSampleOpportunity(
  id: string,
  title: string,
  address: string,
  city: string,
  province: 'Gauteng' | 'Western Cape' | 'KwaZulu-Natal',
  source: any,
  purchasePrice: number,
  openMarketValue: number,
  rehabCost: number,
  monthlyRent: number,
  levies: number,
  rates: number,
  exitPrice: number,
  ltv: number,
  status: any,
  isSection13Eligible: boolean = false,
  driveVault?: any,
  amenityDistances?: {
    schools: any;
    policeStation: any;
    medicalClinic: any;
    shoppingMall: any;
  }
): OpportunityDeal {
  const costs = computeAcquisitionCosts(purchasePrice, ltv);
  const metrics = calculateDealMetrics({
    purchasePrice,
    estimatedRehabCost: rehabCost,
    monthlyRentalEstimate: monthlyRent,
    monthlyLevies: levies,
    monthlyRatesTaxes: rates,
    annualInsurance: 8_400,
    managementFeePercent: 8,
    vacancyRatePercent: 5,
    targetExitPrice: exitPrice,
    holdingPeriodMonths: 6,
    loanToValuePercent: ltv,
    interestRatePercent: 11.75,
    loanTermYears: 20,
    costs,
  });

  const { builtInEquityZAR, builtInEquityPercent } = computeBuiltInEquity(openMarketValue, purchasePrice);
  const amenityScorecard = computeAmenityScore(
    amenityDistances ?? {
      schools: '0-5km',
      policeStation: '0-5km',
      medicalClinic: '0-5km',
      shoppingMall: '0-5km',
    }
  );

  return {
    id,
    title,
    address,
    city,
    province,
    source,
    openMarketValueZAR: openMarketValue,
    purchasePrice,
    builtInEquityZAR,
    builtInEquityPercent,
    amenityScorecard,
    estimatedRehabCost: rehabCost,
    monthlyRentalEstimate: monthlyRent,
    monthlyLevies: levies,
    monthlyRatesTaxes: rates,
    annualInsurance: 8_400,
    managementFeePercent: 8,
    vacancyRatePercent: 5,
    targetExitPrice: exitPrice,
    holdingPeriodMonths: 6,
    loanToValuePercent: ltv,
    interestRatePercent: 11.75,
    loanTermYears: 20,
    costs,
    section13sex: isSection13Eligible ? calculateSection13sex(purchasePrice, 27, true) : undefined,
    driveVault,
    grossYield: metrics.grossYield,
    capRate: metrics.capRate,
    netRoi: metrics.netRoi,
    monthlyCashFlow: metrics.monthlyCashFlow,
    projectedFlipNetProfit: metrics.projectedFlipNetProfit,
    projectedFlipRoi: metrics.projectedFlipRoi,
    status,
    createdAt: '2026-09-15',
  };
}

export const INITIAL_OPPORTUNITIES: OpportunityDeal[] = [
  createSampleOpportunity(
    'opp-1',
    'Parkhurst Distressed Sheriff Auction',
    '42 4th Avenue, Parkhurst',
    'Johannesburg',
    'Gauteng',
    'High-Street Auction',
    1_750_000,
    2_150_000, // Open Market Value (R400k built-in equity)
    450_000,
    22_000,
    0, // Freehold
    1_850,
    2_850_000,
    0, // Cash auction purchase
    'Under Due Diligence',
    false,
    {
      masterFolderUrl: 'https://drive.google.com/drive/folders/parkhurst-sheriff-auction',
      otpDocumentUrl: 'https://drive.google.com/file/d/sheriff-conditions-of-sale/view',
    },
    {
      schools: '0-5km',
      policeStation: '0-5km',
      medicalClinic: '0-5km',
      shoppingMall: '0-5km',
    }
  ),
  createSampleOpportunity(
    'opp-2',
    'Greencreek Riverwalk Developer Unit',
    'Greencreek Estate, Pretoria East',
    'Pretoria',
    'Gauteng',
    'iGrow Rentals',
    899_000,
    1_050_000, // Open Market Value (R151k built-in equity)
    0, // Brand new
    8_500,
    950,
    650,
    1_150_000,
    90,
    'Analyzing',
    true, // Section 13sex Eligible (Off-plan developer unit)
    {
      masterFolderUrl: 'https://drive.google.com/drive/folders/greencreek-developer-unit',
      otpDocumentUrl: 'https://drive.google.com/file/d/greencreek-dev-contract/view',
    },
    {
      schools: '0-5km',
      policeStation: '6-10km',
      medicalClinic: '6-10km',
      shoppingMall: '0-5km',
    }
  ),
  createSampleOpportunity(
    'opp-3',
    'Bree Street City Bowl Studio',
    '155 Bree Street, CBD',
    'Cape Town',
    'Western Cape',
    'Private Agent',
    1_850_000,
    2_250_000, // Open Market Value (R400k built-in equity)
    120_000,
    17_500,
    2_100,
    1_250,
    2_450_000,
    80,
    'Offer Submitted',
    false,
    undefined,
    {
      schools: '0-5km',
      policeStation: '0-5km',
      medicalClinic: '0-5km',
      shoppingMall: '0-5km',
    }
  ),
];

export const INITIAL_INVESTOR_PROFILE: InvestorProfile = {
  entityName: 'L&M Property Investments (Pty) Ltd',
  tradingAs: 'L&M Trading & Capital',
  registrationOrId: '2022/498211/07',
  contactNumber: '+27 82 890 4321',
  email: 'invest@lmtrading.co.za',
  website: 'www.lmtrading.co.za',
  physicalAddress: 'Suite 402, The Boulevard Office Park, Cape Town',
  logoBase64: '',
  bioSummary: 'Sole proprietor and syndication vehicle focusing on distressed residential asset acquisition, light-industrial repositioning, and high-yield sectional title developments across the Western Cape and Gauteng corridors.',
  defaultPrimeRatePercent: 11.75,
  baselineHurdleYieldPercent: 10.0,
  defaultAgentCommissionPercent: 5.0,
};
