import {
  RentalProperty,
  FlipProject,
  OpportunityDeal,
  FundingSource,
  LocalSupplier,
  TaskItem,
  InvestorProfile,
  PropertyTitleType,
  AnalyzerDraft,
  AiSettings,
  DealStrategy,
} from '@/types';
import { computeAcquisitionCosts, calculateSection13sex } from '@/lib/calculations/sarsTax';
import {
  calculateDealMetrics,
  computeBuiltInEquity,
  computeAmenityScore,
} from '@/lib/calculations/propertyMetrics';

export const INITIAL_RENTALS: RentalProperty[] = [
  {
    id: 'rental-1',
    title: 'Sandhurst Executive Suite',
    address: '35 Fredman Drive, Sandton',
    city: 'Johannesburg',
    propertyType: 'Sectional Title Apartment',
    source: 'Private Agent',
    agmDate: '2026-11-12',
    marketValueZAR: 2_450_000,
    purchasePriceZAR: 2_100_000,
    purchaseDate: '2023-03-15',
    outstandingBondBalanceZAR: 1_280_000,
    bondInterestRatePercent: 11.75,
    monthlyBondPaymentZAR: 13_850,
    leases: [{
      id: 'lease-1',
      unitName: 'Main Unit',
      tenantName: 'Dr. Thabo Mokoena',
      tenantPhone: '+27 82 456 7890',
      tenantEmail: 'thabo.mokoena@medclinic.co.za',
      leaseStartDate: '2023-04-01',
      leaseEndDate: '2027-03-31',
      monthlyRentZAR: 18_500,
      depositHeldZAR: 37_000,
      annualEscalationPercent: 7.0,
      status: 'Occupied'
    }],
    managementType: 'Agency',
    agencyName: 'Pam Golding Sandton',
    agencyCommissionPercent: 8.0,
    agencyVatApplicable: true,
    agencyContact: '+27 82 555 1234',
    monthlyGrossRentZAR: 18_500,
    monthlyLeviesZAR: 2_850,
    monthlyRatesTaxesZAR: 1_450,
    monthlyAgentFeeZAR: 1_702,
    monthlyMaintenanceReserveZAR: 800,
    unpaidUtilityArrearsZAR: 0,
    status: 'Occupied',
    maintenanceHistory: [
      {
        id: 'maint-1',
        dateLogged: '2026-07-10',
        issueDescription: 'Geyser pressure valve replacement',
        category: 'Plumbing',
        contractorName: 'Sandton Rapid Plumbing',
        costZAR: 2_850,
        status: 'Resolved',
        invoiceRef: 'INV-8821',
      },
      {
        id: 'maint-2',
        dateLogged: '2026-08-22',
        issueDescription: 'Inverter system routine battery check',
        category: 'Electrical',
        contractorName: 'VoltTech Spark Services',
        costZAR: 1_200,
        status: 'Resolved',
        invoiceRef: 'INV-9014',
      },
    ],
    cocChecklist: {
      electrical: { type: 'Electrical', status: 'Certified / Valid', issueDate: '2026-03-20', certificateNumber: 'EC-99214' },
      gas: { type: 'Gas', status: 'Not Applicable' },
      electricFence: { type: 'Electric Fence', status: 'Not Applicable' },
      plumbing: { type: 'Plumbing (Cape Town)', status: 'Not Applicable' },
      beetle: { type: 'Beetle', status: 'Not Applicable' },
    },
    driveVault: {
      masterFolderUrl: 'https://onedrive.live.com/?id=Sandhurst-Suite-35Fredman',
      otpDocumentUrl: 'https://onedrive.live.com/?id=Signed-Lease-OTP-Sandhurst',
      ratesBillUrl: 'https://onedrive.live.com/?id=Jhb-Rates-Levies-Sandhurst',
      titleDeedUrl: 'https://onedrive.live.com/?id=Sandhurst-Sectional-Title-Deed',
    },
    utilityStatements: [
      {
        id: 'util-sandhurst-2026-02',
        statementDate: '2026-02-05',
        billingPeriod: 'February 2026',
        accountNumber: '553667195',
        provider: 'City of Johannesburg',
        electricityZAR: 480.0,
        waterZAR: 290.0,
        refuseZAR: 353.05,
        sewerageZAR: 320.0,
        propertyRatesZAR: 774.86,
        totalDueZAR: 2217.91,
        parsedVia: 'regex-fallback',
        extractedMeterReadings: [
          {
            date: '2026-02-06',
            utilityType: 'water',
            readingValue: 1934.0,
            previousReadingValue: 1914.0,
            consumption: 20.0,
            meterNumber: '211001886',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'CoJ statement baseline',
          },
          {
            date: '2026-02-26',
            utilityType: 'electricity',
            readingValue: 39504.0,
            previousReadingValue: 39302.0,
            consumption: 202.0,
            meterNumber: '10003374',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'Eskom invoice period 2026/02/17 - 2026/02/26',
          },
        ],
        createdAt: '2026-02-06T10:00:00Z',
      },
      {
        id: 'util-sandhurst-2026-03',
        statementDate: '2026-03-05',
        billingPeriod: 'March 2026',
        accountNumber: '553667195',
        provider: 'City of Johannesburg',
        electricityZAR: 510.0,
        waterZAR: 310.0,
        refuseZAR: 353.05,
        sewerageZAR: 320.0,
        propertyRatesZAR: 774.86,
        totalDueZAR: 2267.91,
        parsedVia: 'regex-fallback',
        extractedMeterReadings: [
          {
            date: '2026-03-08',
            utilityType: 'water',
            readingValue: 1956.0,
            previousReadingValue: 1934.0,
            consumption: 22.0,
            meterNumber: '211001886',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'CoJ statement baseline',
          },
          {
            date: '2026-03-22',
            utilityType: 'electricity',
            readingValue: 39700.0,
            previousReadingValue: 39504.0,
            consumption: 196.0,
            meterNumber: '10003374',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'Eskom invoice period 2026/02/26 - 2026/03/22',
          },
        ],
        createdAt: '2026-03-06T10:00:00Z',
      },
      {
        id: 'util-sandhurst-2026-04',
        statementDate: '2026-04-03',
        billingPeriod: 'April 2026',
        accountNumber: '553667195',
        provider: 'City of Johannesburg',
        electricityZAR: 540.0,
        waterZAR: 330.0,
        refuseZAR: 353.05,
        sewerageZAR: 320.0,
        propertyRatesZAR: 774.86,
        totalDueZAR: 2317.91,
        parsedVia: 'regex-fallback',
        extractedMeterReadings: [
          {
            date: '2026-04-09',
            utilityType: 'water',
            readingValue: 1977.0,
            previousReadingValue: 1956.0,
            consumption: 21.0,
            meterNumber: '211001886',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'CoJ statement reading period 2026/03/08 - 2026/04/09',
          },
          {
            date: '2026-04-20',
            utilityType: 'electricity',
            readingValue: 39910.0,
            previousReadingValue: 39700.0,
            consumption: 210.0,
            meterNumber: '10003374',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'Eskom invoice period 2026/03/22 - 2026/04/20',
          },
        ],
        createdAt: '2026-04-04T10:00:00Z',
      },
    ],
    meterReadings: [
      {
        id: 'meter-seed-water-2',
        date: '2026-04-09',
        utilityType: 'water',
        readingValue: 1977.0,
        previousReadingValue: 1956.0,
        consumption: 21.0,
        meterNumber: '211001886',
        readingType: 'Actual',
        source: 'pdf-extracted',
        notes: 'CoJ statement reading period 2026/03/08 - 2026/04/09',
        createdAt: '2026-04-10T08:00:00Z',
      },
      {
        id: 'meter-seed-water-1',
        date: '2026-03-08',
        utilityType: 'water',
        readingValue: 1956.0,
        previousReadingValue: 1934.0,
        consumption: 22.0,
        meterNumber: '211001886',
        readingType: 'Actual',
        source: 'pdf-extracted',
        notes: 'CoJ statement baseline',
        createdAt: '2026-03-09T08:00:00Z',
      },
      {
        id: 'meter-seed-water-0',
        date: '2026-02-06',
        utilityType: 'water',
        readingValue: 1934.0,
        previousReadingValue: 1914.0,
        consumption: 20.0,
        meterNumber: '211001886',
        readingType: 'Actual',
        source: 'pdf-extracted',
        notes: 'CoJ statement baseline',
        createdAt: '2026-02-07T08:00:00Z',
      },
      {
        id: 'meter-seed-elec-3',
        date: '2026-04-20',
        utilityType: 'electricity',
        readingValue: 39910.0,
        previousReadingValue: 39700.0,
        consumption: 210.0,
        meterNumber: '10003374',
        readingType: 'Actual',
        source: 'pdf-extracted',
        notes: 'Eskom invoice period 2026/03/22 - 2026/04/20',
        createdAt: '2026-04-21T08:00:00Z',
      },
      {
        id: 'meter-seed-elec-2',
        date: '2026-03-22',
        utilityType: 'electricity',
        readingValue: 39700.0,
        previousReadingValue: 39504.0,
        consumption: 196.0,
        meterNumber: '10003374',
        readingType: 'Actual',
        source: 'pdf-extracted',
        notes: 'Eskom invoice period 2026/02/26 - 2026/03/22',
        createdAt: '2026-03-23T08:00:00Z',
      },
      {
        id: 'meter-seed-elec-1',
        date: '2026-02-26',
        utilityType: 'electricity',
        readingValue: 39504.0,
        previousReadingValue: 39302.0,
        consumption: 202.0,
        meterNumber: '10003374',
        readingType: 'Actual',
        source: 'pdf-extracted',
        notes: 'Eskom invoice period 2026/02/17 - 2026/02/26',
        createdAt: '2026-02-27T08:00:00Z',
      },
    ],
  },
  {
    id: 'rental-2',
    title: 'Umhlanga Ridge Coastal Vista',
    address: '14 The Boulevard, Umhlanga Ridge',
    city: 'Durban',
    propertyType: 'Sectional Title Apartment',
    source: 'Direct Owner',
    agmDate: '2026-10-14',
    marketValueZAR: 1_850_000,
    purchasePriceZAR: 1_650_000,
    purchaseDate: '2023-09-01',
    outstandingBondBalanceZAR: 940_000,
    bondInterestRatePercent: 11.5,
    monthlyBondPaymentZAR: 10_020,
    leases: [{
      id: 'lease-2',
      unitName: 'Main Unit',
      tenantName: 'Priya Pillay',
      tenantPhone: '+27 83 912 3456',
      tenantEmail: 'priya.pillay@oceanlogistics.co.za',
      leaseStartDate: '2023-10-01',
      leaseEndDate: '2026-11-30',
      monthlyRentZAR: 15_200,
      depositHeldZAR: 30_400,
      annualEscalationPercent: 6.5,
      status: 'Occupied'
    }],
    managementType: 'Self-Managed',
    agencyCommissionPercent: 0,
    agencyVatApplicable: false,
    agencyContact: '',
    monthlyGrossRentZAR: 15_200,
    monthlyLeviesZAR: 2_150,
    monthlyRatesTaxesZAR: 1_180,
    monthlyAgentFeeZAR: 0,
    monthlyMaintenanceReserveZAR: 600,
    unpaidUtilityArrearsZAR: 3_850,
    status: 'Occupied',
    maintenanceHistory: [
      {
        id: 'maint-3',
        dateLogged: '2026-08-14',
        issueDescription: 'Balcony sliding door roller track repair',
        category: 'General Wear',
        contractorName: 'KZN Aluminium Works',
        costZAR: 1_650,
        status: 'Resolved',
        invoiceRef: 'KZN-4412',
      },
    ],
    utilityStatements: [
      {
        id: 'util-umhlanga-2026-02',
        statementDate: '2026-02-07',
        billingPeriod: 'February 2026',
        accountNumber: '832049182',
        provider: 'eThekwini Municipality',
        electricityZAR: 890.0,
        waterZAR: 360.0,
        refuseZAR: 215.0,
        sewerageZAR: 195.0,
        propertyRatesZAR: 1180.0,
        totalDueZAR: 2840.0,
        parsedVia: 'regex-fallback',
        extractedMeterReadings: [
          {
            date: '2026-02-05',
            utilityType: 'water',
            readingValue: 1452.0,
            previousReadingValue: 1437.0,
            consumption: 15.0,
            meterNumber: 'ETH-W-77491',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'eThekwini water meter reading',
          },
          {
            date: '2026-02-05',
            utilityType: 'electricity',
            readingValue: 27780.0,
            previousReadingValue: 27480.0,
            consumption: 300.0,
            meterNumber: 'ETH-E-33019',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'eThekwini electricity meter reading',
          },
        ],
        createdAt: '2026-02-08T10:00:00Z',
      },
      {
        id: 'util-umhlanga-2026-03',
        statementDate: '2026-03-06',
        billingPeriod: 'March 2026',
        accountNumber: '832049182',
        provider: 'eThekwini Municipality',
        electricityZAR: 940.0,
        waterZAR: 390.0,
        refuseZAR: 215.0,
        sewerageZAR: 195.0,
        propertyRatesZAR: 1180.0,
        totalDueZAR: 2920.0,
        parsedVia: 'regex-fallback',
        extractedMeterReadings: [
          {
            date: '2026-03-05',
            utilityType: 'water',
            readingValue: 1468.0,
            previousReadingValue: 1452.0,
            consumption: 16.0,
            meterNumber: 'ETH-W-77491',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'eThekwini water meter reading',
          },
          {
            date: '2026-03-05',
            utilityType: 'electricity',
            readingValue: 28090.0,
            previousReadingValue: 27780.0,
            consumption: 310.0,
            meterNumber: 'ETH-E-33019',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'eThekwini electricity meter reading',
          },
        ],
        createdAt: '2026-03-07T10:00:00Z',
      },
      {
        id: 'util-umhlanga-2026-04',
        statementDate: '2026-04-06',
        billingPeriod: 'April 2026',
        accountNumber: '832049182',
        provider: 'eThekwini Municipality',
        electricityZAR: 980.0,
        waterZAR: 410.0,
        refuseZAR: 215.0,
        sewerageZAR: 195.0,
        propertyRatesZAR: 1180.0,
        totalDueZAR: 2980.0,
        parsedVia: 'regex-fallback',
        extractedMeterReadings: [
          {
            date: '2026-04-05',
            utilityType: 'water',
            readingValue: 1485.0,
            previousReadingValue: 1468.0,
            consumption: 17.0,
            meterNumber: 'ETH-W-77491',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'eThekwini water meter reading',
          },
          {
            date: '2026-04-05',
            utilityType: 'electricity',
            readingValue: 28410.0,
            previousReadingValue: 28090.0,
            consumption: 320.0,
            meterNumber: 'ETH-E-33019',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'eThekwini electricity meter reading',
          },
        ],
        createdAt: '2026-04-07T10:00:00Z',
      },
    ],
    meterReadings: [
      {
        id: 'meter-umhlanga-water-2',
        date: '2026-04-05',
        utilityType: 'water',
        readingValue: 1485.0,
        previousReadingValue: 1468.0,
        consumption: 17.0,
        meterNumber: 'ETH-W-77491',
        readingType: 'Actual',
        source: 'pdf-extracted',
        notes: 'eThekwini water meter reading',
        createdAt: '2026-04-06T08:00:00Z',
      },
      {
        id: 'meter-umhlanga-water-1',
        date: '2026-03-05',
        utilityType: 'water',
        readingValue: 1468.0,
        previousReadingValue: 1452.0,
        consumption: 16.0,
        meterNumber: 'ETH-W-77491',
        readingType: 'Actual',
        source: 'pdf-extracted',
        notes: 'eThekwini water meter reading',
        createdAt: '2026-03-06T08:00:00Z',
      },
      {
        id: 'meter-umhlanga-elec-dispute-1',
        date: '2026-04-06',
        utilityType: 'electricity',
        readingValue: 28260.0,
        previousReadingValue: 28090.0,
        consumption: 170.0,
        meterNumber: 'ETH-E-33019',
        readingType: 'Actual',
        source: 'manual',
        photoUrl: 'https://photos.app.goo.gl/UmhlangaMeterApr2026',
        notes: 'Physical on-site reading: dials show 28,260 kWh. eThekwini statement estimated 28,410 kWh.',
        createdAt: '2026-04-06T14:30:00Z',
        isDisputed: true,
        disputeStatus: 'Open / Lodged',
        disputeReason: 'council_over_estimate',
        disputeReferenceNumber: 'ETH-2026-88192',
        disputedStatementId: 'util-umhlanga-2026-04',
        disputedMunicipalReadingValue: 28410.0,
        disputeDifferenceConsumption: 150.0,
        disputeEffectiveTariffPerUnit: 3.0625,
        disputeEstimatedRandImpactZAR: 459.38,
        disputeLodgedDate: '2026-04-07',
        disputeResolutionNotes: 'Lodged ticket via eThekwini Smart Services portal. Technician inspection requested.',
      },
      {
        id: 'meter-umhlanga-elec-2',
        date: '2026-04-05',
        utilityType: 'electricity',
        readingValue: 28410.0,
        previousReadingValue: 28090.0,
        consumption: 320.0,
        meterNumber: 'ETH-E-33019',
        readingType: 'Actual',
        source: 'pdf-extracted',
        notes: 'eThekwini electricity meter reading',
        createdAt: '2026-04-06T08:00:00Z',
      },
      {
        id: 'meter-umhlanga-elec-1',
        date: '2026-03-05',
        utilityType: 'electricity',
        readingValue: 28090.0,
        previousReadingValue: 27780.0,
        consumption: 310.0,
        meterNumber: 'ETH-E-33019',
        readingType: 'Actual',
        source: 'pdf-extracted',
        notes: 'eThekwini electricity meter reading',
        createdAt: '2026-03-06T08:00:00Z',
      },
    ],
  },
  {
    id: 'rental-3',
    title: 'Green Point Urban Loft',
    address: '88 Somerset Road, Green Point',
    city: 'Cape Town',
    propertyType: 'Sectional Title Apartment',
    source: 'Private Agent',
    agmDate: '2027-02-18',
    marketValueZAR: 3_200_000,
    purchasePriceZAR: 2_750_000,
    purchaseDate: '2022-11-10',
    outstandingBondBalanceZAR: 1_550_000,
    bondInterestRatePercent: 11.25,
    monthlyBondPaymentZAR: 16_240,
    leases: [{
      id: 'lease-3',
      unitName: 'Main Unit',
      tenantName: 'Matthew van der Merwe',
      tenantPhone: '+27 71 889 0012',
      tenantEmail: 'matthew.vdm@capetech.io',
      leaseStartDate: '2024-01-01',
      leaseEndDate: '2026-12-31',
      monthlyRentZAR: 24_500,
      depositHeldZAR: 49_000,
      annualEscalationPercent: 8.0,
      status: 'Occupied'
    }],
    managementType: 'Agency',
    agencyName: 'RE/MAX Living Cape Town',
    agencyCommissionPercent: 8.0,
    agencyVatApplicable: true,
    agencyContact: '+27 71 889 0012',
    monthlyGrossRentZAR: 24_500,
    monthlyLeviesZAR: 3_200,
    monthlyRatesTaxesZAR: 1_950,
    monthlyAgentFeeZAR: 2_254,
    monthlyMaintenanceReserveZAR: 1_000,
    unpaidUtilityArrearsZAR: 0,
    status: 'Occupied',
    maintenanceHistory: [],
    utilityStatements: [
      {
        id: 'util-greenpoint-2026-02',
        statementDate: '2026-02-10',
        billingPeriod: 'February 2026',
        accountNumber: '100482937',
        provider: 'City of Cape Town',
        electricityZAR: 1120.0,
        waterZAR: 390.0,
        refuseZAR: 260.0,
        sewerageZAR: 240.0,
        propertyRatesZAR: 1950.0,
        totalDueZAR: 3960.0,
        parsedVia: 'regex-fallback',
        extractedMeterReadings: [
          {
            date: '2026-02-09',
            utilityType: 'water',
            readingValue: 1777.0,
            previousReadingValue: 1761.0,
            consumption: 16.0,
            meterNumber: 'CCT-W-99120',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'City of Cape Town water reading',
          },
          {
            date: '2026-02-09',
            utilityType: 'electricity',
            readingValue: 41160.0,
            previousReadingValue: 40790.0,
            consumption: 370.0,
            meterNumber: 'CCT-E-55418',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'City of Cape Town electricity reading',
          },
        ],
        createdAt: '2026-02-11T10:00:00Z',
      },
      {
        id: 'util-greenpoint-2026-03',
        statementDate: '2026-03-10',
        billingPeriod: 'March 2026',
        accountNumber: '100482937',
        provider: 'City of Cape Town',
        electricityZAR: 1180.0,
        waterZAR: 420.0,
        refuseZAR: 260.0,
        sewerageZAR: 240.0,
        propertyRatesZAR: 1950.0,
        totalDueZAR: 4050.0,
        parsedVia: 'regex-fallback',
        extractedMeterReadings: [
          {
            date: '2026-03-09',
            utilityType: 'water',
            readingValue: 1794.0,
            previousReadingValue: 1777.0,
            consumption: 17.0,
            meterNumber: 'CCT-W-99120',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'City of Cape Town water reading',
          },
          {
            date: '2026-03-09',
            utilityType: 'electricity',
            readingValue: 41530.0,
            previousReadingValue: 41160.0,
            consumption: 370.0,
            meterNumber: 'CCT-E-55418',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'City of Cape Town electricity reading',
          },
        ],
        createdAt: '2026-03-11T10:00:00Z',
      },
      {
        id: 'util-greenpoint-2026-04',
        statementDate: '2026-04-08',
        billingPeriod: 'April 2026',
        accountNumber: '100482937',
        provider: 'City of Cape Town',
        electricityZAR: 1240.0,
        waterZAR: 440.0,
        refuseZAR: 260.0,
        sewerageZAR: 240.0,
        propertyRatesZAR: 1950.0,
        totalDueZAR: 4130.0,
        parsedVia: 'regex-fallback',
        extractedMeterReadings: [
          {
            date: '2026-04-07',
            utilityType: 'water',
            readingValue: 1812.0,
            previousReadingValue: 1794.0,
            consumption: 18.0,
            meterNumber: 'CCT-W-99120',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'City of Cape Town water reading',
          },
          {
            date: '2026-04-07',
            utilityType: 'electricity',
            readingValue: 41920.0,
            previousReadingValue: 41530.0,
            consumption: 390.0,
            meterNumber: 'CCT-E-55418',
            readingType: 'Actual',
            source: 'pdf-extracted',
            notes: 'City of Cape Town electricity reading',
          },
        ],
        createdAt: '2026-04-09T10:00:00Z',
      },
    ],
    meterReadings: [
      {
        id: 'meter-greenpoint-water-2',
        date: '2026-04-07',
        utilityType: 'water',
        readingValue: 1812.0,
        previousReadingValue: 1794.0,
        consumption: 18.0,
        meterNumber: 'CCT-W-99120',
        readingType: 'Actual',
        source: 'pdf-extracted',
        notes: 'City of Cape Town water reading',
        createdAt: '2026-04-08T08:00:00Z',
      },
      {
        id: 'meter-greenpoint-water-1',
        date: '2026-03-09',
        utilityType: 'water',
        readingValue: 1794.0,
        previousReadingValue: 1777.0,
        consumption: 17.0,
        meterNumber: 'CCT-W-99120',
        readingType: 'Actual',
        source: 'pdf-extracted',
        notes: 'City of Cape Town water reading',
        createdAt: '2026-03-10T08:00:00Z',
      },
      {
        id: 'meter-greenpoint-elec-2',
        date: '2026-04-07',
        utilityType: 'electricity',
        readingValue: 41920.0,
        previousReadingValue: 41530.0,
        consumption: 390.0,
        meterNumber: 'CCT-E-55418',
        readingType: 'Actual',
        source: 'pdf-extracted',
        notes: 'City of Cape Town electricity reading',
        createdAt: '2026-04-08T08:00:00Z',
      },
      {
        id: 'meter-greenpoint-elec-1',
        date: '2026-03-09',
        utilityType: 'electricity',
        readingValue: 41530.0,
        previousReadingValue: 41160.0,
        consumption: 370.0,
        meterNumber: 'CCT-E-55418',
        readingType: 'Actual',
        source: 'pdf-extracted',
        notes: 'City of Cape Town electricity reading',
        createdAt: '2026-03-10T08:00:00Z',
      },
    ],
  },
  {
    id: 'rental-4',
    title: '42 Kruger St, Krugersdorp',
    address: '42 Kruger Street, Krugersdorp CBD',
    city: 'Krugersdorp',
    propertyType: 'Freehold House',
    source: 'Direct Owner',
    marketValueZAR: 1_100_000,
    purchasePriceZAR: 680_000,
    purchaseDate: '2026-01-15',
    outstandingBondBalanceZAR: 520_000,
    bondInterestRatePercent: 11.5,
    monthlyBondPaymentZAR: 5_620,
    isBrrrrProperty: true,
    leases: [
      {
        id: 'lease-4a',
        unitName: 'Main House',
        tenantName: 'Sipho Ndlovu',
        tenantPhone: '+27 76 321 4567',
        tenantEmail: 'sipho.ndlovu@gmail.com',
        leaseStartDate: '2026-02-01',
        leaseEndDate: '2027-01-31',
        monthlyRentZAR: 5_500,
        depositHeldZAR: 5_500,
        annualEscalationPercent: 7.0,
        status: 'Occupied',
      },
      {
        id: 'lease-4b',
        unitName: 'Cottage A (backyard)',
        tenantName: 'Grace Mokoena',
        tenantPhone: '+27 83 654 9012',
        tenantEmail: 'grace.mokoena@outlook.com',
        leaseStartDate: '2026-03-01',
        leaseEndDate: '2027-02-28',
        monthlyRentZAR: 3_200,
        depositHeldZAR: 3_200,
        annualEscalationPercent: 6.5,
        status: 'Occupied',
      },
      {
        id: 'lease-4c',
        unitName: 'Cottage B (backyard)',
        tenantName: '',
        leaseStartDate: '2026-04-01',
        leaseEndDate: '2027-03-31',
        monthlyRentZAR: 2_800,
        depositHeldZAR: 0,
        annualEscalationPercent: 6.5,
        status: 'Vacant',
      },
    ],
    ancillaryIncomes: [
      {
        id: 'anc-4a',
        type: 'cell_tower',
        tenantName: 'Vodacom (ATC Towers)',
        monthlyRentZAR: 8_500,
        annualEscalationPercent: 7,
        contractStartDate: '2023-01-01',
        contractEndDate: '2033-01-01',
        vatApplicable: true,
        notes: 'Rooftop cell tower lease — 10-year contract with ATC on behalf of Vodacom',
      },
      {
        id: 'anc-4b',
        type: 'billboard',
        tenantName: 'Primedia Outdoor',
        monthlyRentZAR: 4_200,
        annualEscalationPercent: 6,
        contractStartDate: '2024-06-01',
        contractEndDate: '2029-06-01',
        vatApplicable: true,
        notes: 'Street-facing billboard on boundary wall — 5-year outdoor advertising lease',
      },
    ],
    managementType: 'Self-Managed',
    agencyCommissionPercent: 0,
    agencyVatApplicable: false,
    agencyContact: '',
    monthlyGrossRentZAR: 11_500,
    monthlyLeviesZAR: 0,
    monthlyRatesTaxesZAR: 980,
    monthlyAgentFeeZAR: 0,
    monthlyMaintenanceReserveZAR: 450,
    annualBuildingInsuranceZAR: 4_800,
    unpaidUtilityArrearsZAR: 0,
    status: 'Occupied',
    utilityType: 'hybrid',
    prepaidVendorName: 'Citiq Prepaid',
    monthlyPrepaidVendingFeeZAR: 850,
    section13sexAnnualShieldZAR: 9_350,
    maintenanceHistory: [
      {
        id: 'maint-4a',
        dateLogged: '2026-06-18',
        issueDescription: 'Cottage B geyser replacement (160L low-pressure)',
        category: 'Plumbing',
        contractorName: 'West Rand Plumbing Co.',
        costZAR: 4_200,
        status: 'Resolved',
        invoiceRef: 'WRP-1102',
      },
    ],
    driveVault: {
      masterFolderUrl: 'https://onedrive.live.com/?id=Kruger-42-Krugersdorp',
      titleDeedUrl: 'https://onedrive.live.com/?id=Kruger-42-Title-Deed',
    },
    utilityStatements: [],
    meterReadings: [],
  },
];

export const INITIAL_FLIPS: FlipProject[] = [
  {
    id: 'flip-1',
    title: 'Kloof Street Heritage Redesign',
    address: '74 Kloof Street, Gardens',
    city: 'Cape Town',
    propertyType: 'Freehold House',
    source: 'Private Agent',
    purchaseDate: '2026-03-01',
    purchasePriceZAR: 3_800_000,
    acquisitionCostsZAR: 315_000,
    baselineRenovationBudgetZAR: 750_000,
    strategy: 'Flip',
    estimatedDurationMonths: 6,
    monthlyHoldingCostZAR: 22_500,
    monthlyBondPaymentZAR: 16_000,
    monthlyLeviesZAR: 0, // Freehold title strictly R0 levies
    monthlyRatesTaxesZAR: 4_500,
    monthlyOtherHoldingCostZAR: 2_000,
    targetExitPriceZAR: 5_650_000,
    targetCompletionDate: '2026-11-15',
    taxEntityType: 'Company (27%)',
    municipalClearance: {
      sec118ArrearsZAR: 14_500,
      advanceCouncilDepositZAR: 26_000,
      rccStatus: 'Certificate Issued',
      rccApplicationDate: '2026-03-05',
    },
    drawSchedule: {
      depositPaid: true,
      firstFixApproved: true,
      finishesApproved: false,
      retentionReleased: false,
    },
    currentPhase: 'Finishes & Tiling',
    linkedFundingIds: ['fund-1'],
    fundingRequiredZAR: 1_800_000,
    capitalRaisedZAR: 1_500_000,
    primaryFunderName: 'Johan Meyer',
    primaryFunderContact: 'Meyer Family Trust / +27 82 555 1234',
    primaryFunderType: 'Private Lender',
    coFundersNotes: 'R300k balance open for private co-investment tranche',
    promisedReturnType: 'Fixed Interest',
    promisedReturnRatePercent: 14.0,
    promisedPayoutSchedule: 'Monthly Interest',
    securityOffered: '1st registered second-mortgage bond over Kloof Street',
    status: 'Active',
    notes: 'Restoring historic Victorian facade while introducing open-plan modern Scandinavian interior.',
    boq: [
      {
        id: 'boq-1',
        category: 'Demolition & Prep',
        itemDescription: 'Removal of partition walls & asbestos roof shed demolition',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 45_000,
        baselineTotalZAR: 45_000,
        actualCostZAR: 42_500,
        varianceZAR: -2_500,
        supplierOrContractor: 'Cape Strip & Demolition Co.',
        status: 'Completed',
        milestonePhase: 'Deposit',
        retentionPercent: 0,
        invoiceRef: 'CSD-019',
      },
      {
        id: 'boq-2',
        category: 'Electrical & Lighting',
        itemDescription: 'Full rewiring, recessed LED downlights, and 8kVA Sunsynk Solar Inverter',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 140_000,
        baselineTotalZAR: 140_000,
        actualCostZAR: 148_000,
        varianceZAR: 8_000,
        supplierOrContractor: 'Master Electricians CT (Wireman CoC)',
        status: 'In Progress',
        milestonePhase: 'First Fix / Wet Works',
        retentionPercent: 10,
        invoiceRef: 'MEC-441',
      },
      {
        id: 'boq-3',
        category: 'Plumbing & Wet Works',
        itemDescription: 'Re-pipe copper to PEX, install concealed cisterns & freestanding bath',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 95_000,
        baselineTotalZAR: 95_000,
        actualCostZAR: 91_200,
        varianceZAR: -3_800,
        supplierOrContractor: 'Plumblink Foreshore / Cape Coastal Plumbing',
        status: 'In Progress',
        milestonePhase: 'First Fix / Wet Works',
        retentionPercent: 10,
        invoiceRef: 'CCP-992',
      },
      {
        id: 'boq-4',
        category: 'Kitchen & Cabinetry',
        itemDescription: 'Custom matte charcoal soft-close joinery & engineered quartz countertops',
        unit: 'linear m',
        quantity: 12,
        baselineUnitCostZAR: 16_000,
        baselineTotalZAR: 192_000,
        actualCostZAR: 188_000,
        varianceZAR: -4_000,
        supplierOrContractor: 'Elite Joinery Paarden Eiland',
        status: 'In Progress',
        milestonePhase: 'Finishes',
        retentionPercent: 10,
        isSponsoredOrBarter: true,
        commercialRetailValueZAR: 235_000,
        actualCashOutflowZAR: 188_000,
      },
      {
        id: 'boq-5',
        category: 'Flooring & Tiling',
        itemDescription: 'Herringbone vinyl luxury planks & 1200x600 porcelain bathroom tiles',
        unit: 'm2',
        quantity: 140,
        baselineUnitCostZAR: 850,
        baselineTotalZAR: 119_000,
        actualCostZAR: 124_000,
        varianceZAR: 5_000,
        supplierOrContractor: 'Tile Africa Northgate / Builders Warehouse',
        status: 'In Progress',
        milestonePhase: 'Finishes',
        retentionPercent: 10,
        isSponsoredOrBarter: true,
        commercialRetailValueZAR: 160_000,
        actualCashOutflowZAR: 124_000,
      },
      {
        id: 'boq-6',
        category: 'Painting & Finishes',
        itemDescription: 'Plascon Double Velvet interior & Micatex exterior weather shield',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 75_000,
        baselineTotalZAR: 75_000,
        actualCostZAR: 70_000,
        varianceZAR: -5_000,
        supplierOrContractor: 'ProCoat Painters Cape',
        status: 'Quoted',
        milestonePhase: 'Retention',
        retentionPercent: 20,
      },
    ],
    cocChecklist: {
      electrical: { type: 'Electrical', status: 'Pending Inspection' },
      gas: { type: 'Gas', status: 'Pending Inspection' },
      electricFence: { type: 'Electric Fence', status: 'Not Applicable' },
      plumbing: { type: 'Plumbing (Cape Town)', status: 'Pending Inspection' },
      beetle: { type: 'Beetle', status: 'Certified / Valid', issueDate: '2026-08-10', certificateNumber: 'BC-99104' },
    },
    driveVault: {
      masterFolderUrl: 'https://1drv.ms/f/s!Am8KloofHeritageFlipCapeTown',
      otpDocumentUrl: 'https://1drv.ms/b/s!Am8SignedOTP-Kloof74',
      ratesBillUrl: 'https://1drv.ms/b/s!Am8CapeTownRates-Aug2026',
      titleDeedUrl: 'https://1drv.ms/b/s!Am8SG-Diagram-TitleDeed-CapeTown',
    },
  },
  {
    id: 'flip-2',
    title: 'Waterkloof Diplomatic Fixer',
    address: '112 Crown Avenue, Waterkloof',
    city: 'Pretoria',
    propertyType: 'Townhouse / Cluster',
    source: 'Distressed Sale / Repo',
    agmDate: '2026-11-20',
    purchaseDate: '2026-05-15',
    purchasePriceZAR: 2_100_000,
    acquisitionCostsZAR: 148_000,
    baselineRenovationBudgetZAR: 480_000,
    strategy: 'Flip',
    estimatedDurationMonths: 7,
    monthlyHoldingCostZAR: 18_000,
    monthlyBondPaymentZAR: 12_500,
    monthlyLeviesZAR: 2_300,
    monthlyRatesTaxesZAR: 1_800,
    monthlyOtherHoldingCostZAR: 1_400,
    targetExitPriceZAR: 3_350_000,
    targetCompletionDate: '2026-12-20',
    taxEntityType: 'Company (27%)',
    municipalClearance: {
      sec118ArrearsZAR: 58_500,
      advanceCouncilDepositZAR: 24_000,
      rccStatus: 'Paid & Awaiting Certificate',
      rccApplicationDate: '2026-05-20',
      disputeNotes: 'City of Tshwane billing query resolved (Ref #TSH-2026-8819); R58,500 paid, awaiting clearance certificate issuance.',
    },
    drawSchedule: {
      depositPaid: true,
      firstFixApproved: false,
      finishesApproved: false,
      retentionReleased: false,
    },
    currentPhase: 'First Fix (Plumbing/Elec)',
    linkedFundingIds: ['fund-2'],
    fundingRequiredZAR: 1_200_000,
    capitalRaisedZAR: 800_000,
    primaryFunderName: 'Protea Property Syndicate',
    primaryFunderContact: 'Kobus van Zyl (MD) / +27 83 777 9876',
    primaryFunderType: 'Syndicate JV Partner',
    coFundersNotes: 'JV syndicate backing the Waterkloof acquisition & BOQ tranche',
    promisedReturnType: 'Equity Profit Split',
    promisedReturnRatePercent: 25.0,
    promisedPayoutSchedule: 'At Exit (Maturity)',
    securityOffered: 'JV Syndicate Profit Participation Agreement',
    status: 'Delayed',
    notes: 'Distressed purchase from bank repo. Converting outdated 3-bed into 4-bed modern family residence with entertainment patio. Delayed due to Tshwane Sec 118 clearance processing.',
    driveVault: {
      masterFolderUrl: 'https://www.dropbox.com/scl/fo/waterkloof-fixer-vault',
      otpDocumentUrl: 'https://www.dropbox.com/scl/fi/waterkloof-otp-signed.pdf',
      ratesBillUrl: 'https://www.dropbox.com/scl/fi/tshwane-rates-statement.pdf',
      titleDeedUrl: 'https://www.dropbox.com/scl/fi/waterkloof-deed-plans.pdf',
    },
    cocChecklist: {
      electrical: { type: 'Electrical', status: 'Pending Inspection' },
      electricFence: { type: 'Electric Fence', status: 'Pending Inspection' },
      gas: { type: 'Gas', status: 'Not Applicable' },
      approvedPlansSG: { type: 'Approved SG Plans', status: 'Pending Inspection', certificateNumber: 'SG-TSHW-2026-194' },
    },
    boq: [
      {
        id: 'boq-7',
        category: 'Demolition & Prep',
        itemDescription: 'Site clearance and pool re-marbelite prep',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 35_000,
        baselineTotalZAR: 35_000,
        actualCostZAR: 35_000,
        varianceZAR: 0,
        supplierOrContractor: 'Pretoria Earthworks',
        status: 'Completed',
        milestonePhase: 'Deposit',
        retentionPercent: 0,
      },
      {
        id: 'boq-8',
        category: 'Roofing & Structural',
        itemDescription: 'Replace broken concrete roof tiles and waterproof flashing',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 65_000,
        baselineTotalZAR: 65_000,
        actualCostZAR: 68_500,
        varianceZAR: 3_500,
        supplierOrContractor: 'Chamberlains Menlyn Hardware',
        status: 'Completed',
        milestonePhase: 'First Fix / Wet Works',
        retentionPercent: 10,
      },
      {
        id: 'boq-9',
        category: 'Electrical & Lighting',
        itemDescription: 'New DB board, perimeter solar security floodlights, smart switches',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 85_000,
        baselineTotalZAR: 85_000,
        actualCostZAR: 78_000,
        varianceZAR: -7_000,
        supplierOrContractor: 'Jakobs Electrical Services',
        status: 'In Progress',
        milestonePhase: 'First Fix / Wet Works',
        retentionPercent: 10,
      },
      {
        id: 'boq-10',
        category: 'Kitchen & Cabinetry',
        itemDescription: 'High-gloss white shaker cabinets & Caesarstone countertops',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 135_000,
        baselineTotalZAR: 135_000,
        actualCostZAR: 135_000,
        varianceZAR: 0,
        supplierOrContractor: 'Leroy Merlin Fourways / Builders',
        status: 'Quoted',
        milestonePhase: 'Finishes',
        retentionPercent: 10,
        isSponsoredOrBarter: true,
        commercialRetailValueZAR: 175_000,
        actualCashOutflowZAR: 135_000,
      },
      {
        id: 'boq-11',
        category: 'Painting & Finishes',
        itemDescription: 'Retention pool & final snagging practical completion sign-off',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 45_000,
        baselineTotalZAR: 45_000,
        actualCostZAR: 45_000,
        varianceZAR: 0,
        supplierOrContractor: 'Main Contractor Retention Pool',
        status: 'Quoted',
        milestonePhase: 'Retention',
        retentionPercent: 20,
      },
    ],
  },
  {
    id: 'flip-3',
    title: 'Linden 1950s Character Home Revival',
    address: '18 8th Street, Linden',
    city: 'Johannesburg',
    propertyType: 'Freehold House',
    source: 'High-Street Auction',
    purchaseDate: '2026-06-10',
    purchasePriceZAR: 1_450_000,
    acquisitionCostsZAR: 98_500,
    baselineRenovationBudgetZAR: 320_000,
    strategy: 'Flip',
    estimatedDurationMonths: 8,
    monthlyHoldingCostZAR: 12_500,
    monthlyBondPaymentZAR: 0, // Cash purchase, no bond
    monthlyLeviesZAR: 0, // Freehold
    monthlyRatesTaxesZAR: 2_100,
    monthlyOtherHoldingCostZAR: 1_800,
    municipalValuationZAR: 1_350_000,
    targetExitPriceZAR: 2_450_000,
    targetCompletionDate: '2027-02-28',
    taxEntityType: 'Individual (45%)', // Sole proprietor — demonstrates 45% SARS provisional tax
    municipalClearance: {
      sec118ArrearsZAR: 32_000,
      advanceCouncilDepositZAR: 12_600, // 6 months rates in advance @ R2,100/mo
      rccStatus: 'Figures Issued', // Demonstrates amber 'Figures Ready' badge in Upcoming Deadlines
      rccApplicationDate: '2026-06-15',
    },
    drawSchedule: {
      depositPaid: true,
      firstFixApproved: false,
      finishesApproved: false,
      retentionReleased: false,
    },
    currentPhase: 'Strip & Demolition',
    linkedFundingIds: [],
    fundingRequiredZAR: 900_000,
    capitalRaisedZAR: 550_000,
    primaryFunderName: 'Friends & Family Pool',
    primaryFunderContact: 'Personal network / +27 82 100 2200',
    primaryFunderType: 'Friends & Family',
    promisedReturnType: 'Fixed Interest',
    promisedReturnRatePercent: 12.0,
    promisedPayoutSchedule: 'At Exit (Maturity)',
    securityOffered: 'Personal suretyship over title deed',
    status: 'Delayed',
    notes: 'Classic Linden 1950s freehold sourced at auction below valuation. Structural wall removal requires RSJ lintels. CoJ Figures Issued — waiting on final clearance certificate.',
    boq: [
      {
        id: 'boq-12',
        category: 'Demolition & Prep',
        itemDescription: 'Full interior strip, non-load-bearing wall removal & RSJ steel lintel installation',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 55_000,
        baselineTotalZAR: 55_000,
        actualCostZAR: 58_500,
        varianceZAR: 3_500,
        supplierOrContractor: 'JHB Strip & Structural',
        status: 'In Progress',
        milestonePhase: 'Deposit',
        retentionPercent: 10,
        invoiceRef: 'JSS-077',
      },
      {
        id: 'boq-13',
        category: 'Electrical & Lighting',
        itemDescription: 'Full rewire, smart DB, exterior security lighting & Eskom upgrade',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 75_000,
        baselineTotalZAR: 75_000,
        actualCostZAR: 0,
        varianceZAR: -75_000,
        supplierOrContractor: 'Builders Warehouse Sandton (materials) / Linden Electrical',
        status: 'Not Started',
        milestonePhase: 'First Fix / Wet Works',
        retentionPercent: 10,
        isSponsoredOrBarter: true,
        commercialRetailValueZAR: 95_000,
        actualCashOutflowZAR: 0,
      },
      {
        id: 'boq-14',
        category: 'Kitchen & Cabinetry',
        itemDescription: 'Flat-pack Sonae Arauco Innovus board kitchen & island installation',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 80_000,
        baselineTotalZAR: 80_000,
        actualCostZAR: 0,
        varianceZAR: -80_000,
        supplierOrContractor: 'Sonae Arauco / Builders Warehouse Sandton',
        status: 'Not Started',
        milestonePhase: 'Finishes',
        retentionPercent: 10,
        isSponsoredOrBarter: true,
        commercialRetailValueZAR: 120_000,
        actualCashOutflowZAR: 0,
      },
      {
        id: 'boq-15',
        category: 'Security & Exterior',
        itemDescription: 'Boundary wall heightening, electric fence & automated gate',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 65_000,
        baselineTotalZAR: 65_000,
        actualCostZAR: 0,
        varianceZAR: -65_000,
        supplierOrContractor: 'Northcliff Security Systems',
        status: 'Not Started',
        milestonePhase: 'Finishes',
        retentionPercent: 10,
      },
      {
        id: 'boq-16',
        category: 'Painting & Finishes',
        itemDescription: 'Practical completion snagging retention — ProCoat JHB final sign-off',
        unit: 'lump sum',
        quantity: 1,
        baselineUnitCostZAR: 45_000,
        baselineTotalZAR: 45_000,
        actualCostZAR: 0,
        varianceZAR: -45_000,
        supplierOrContractor: 'ProCoat JHB',
        status: 'Not Started',
        milestonePhase: 'Retention',
        retentionPercent: 20,
      },
    ],
    cocChecklist: {
      electrical: { type: 'Electrical', status: 'Pending Inspection' },
      electricFence: { type: 'Electric Fence', status: 'Pending Inspection' },
      gas: { type: 'Gas', status: 'Not Applicable' },
      approvedPlansSG: { type: 'Approved SG Plans', status: 'Pending Inspection' },
    },
    driveVault: {
      masterFolderUrl: 'https://1drv.ms/f/s!Am8LindenLidRevival8thStreet',
      otpDocumentUrl: 'https://1drv.ms/b/s!Am8LindenOTP-SignedAuction',
      ratesBillUrl: 'https://1drv.ms/b/s!Am8CoJRatesBill-Linden-Jun2026',
      titleDeedUrl: 'https://1drv.ms/b/s!Am8LindenSGDiagram-Erf18',
    },
  },
];

export const INITIAL_FUNDING: FundingSource[] = [
  {
    id: 'fund-1',
    lenderName: 'Johan Meyer',
    entityOrContact: 'Meyer Family Trust',
    emailPhone: 'johan@meyerholdings.co.za / +27 82 555 1234',
    fundingType: 'Private Lender',
    capitalAmountZAR: 1_500_000,
    disbursementDate: '2026-03-01',
    maturityDate: '2026-11-30',
    originalMaturityDate: '2026-11-30',
    returnTermsType: 'Fixed Interest',
    returnRatePercent: 14.0, // 14% p.a.
    paymentSchedule: 'Monthly Interest',
    linkedDealId: 'flip-1',
    linkedDealName: 'Kloof Street Heritage Redesign',
    totalRepaidZAR: 105_000, // Monthly payments made
    status: 'Active',
    notes: 'First registered second-mortgage bond over Kloof Street. Monthly coupon R17,500.',
    tranches: [
      {
        id: 'tr-1',
        name: 'Tranche 1: Acquisition & Transfer',
        amountZAR: 900_000,
        disbursedDate: '2026-03-01',
        isDisbursed: true,
        linkedMilestonePhase: 'Deposit',
      },
      {
        id: 'tr-2',
        name: 'Tranche 2: First Fix & Structural',
        amountZAR: 400_000,
        disbursedDate: '2026-05-10',
        isDisbursed: true,
        linkedMilestonePhase: 'First Fix / Wet Works',
      },
      {
        id: 'tr-3',
        name: 'Tranche 3: High-End Finishes & Sanitaryware',
        amountZAR: 200_000,
        isDisbursed: false,
        linkedMilestonePhase: 'Finishes',
      },
    ],
  },
  {
    id: 'fund-2',
    lenderName: 'Protea Property Syndicate',
    entityOrContact: 'Kobus van Zyl (MD)',
    emailPhone: 'kobus@proteasyndicate.co.za / +27 83 777 9876',
    fundingType: 'Proposal-backed',
    capitalAmountZAR: 800_000,
    disbursementDate: '2026-05-15',
    maturityDate: '2027-03-01',
    originalMaturityDate: '2026-12-31',
    returnTermsType: 'Equity Profit Split',
    returnRatePercent: 25.0, // 25% share of net flip profit
    paymentSchedule: 'At Exit (Maturity)',
    linkedDealId: 'flip-2',
    linkedDealName: 'Waterkloof Diplomatic Fixer',
    totalRepaidZAR: 0,
    status: 'Active',
    notes: 'JV syndicate backing the Waterkloof acquisition & BOQ tranche.',
    delayExtensionDays: 60,
    delayNotes: '+60d: City of Tshwane Sec 118 rates clearance processing delay',
    tranches: [
      {
        id: 'tr-4',
        name: 'Tranche 1: Auction Deposit & Wet Works',
        amountZAR: 500_000,
        disbursedDate: '2026-05-15',
        isDisbursed: true,
        linkedMilestonePhase: 'Deposit',
      },
      {
        id: 'tr-5',
        name: 'Tranche 2: Renovation & Rates Clearance Float',
        amountZAR: 300_000,
        disbursedDate: '2026-06-01',
        isDisbursed: true,
        linkedMilestonePhase: 'First Fix / Wet Works',
      },
    ],
  },
  {
    id: 'fund-3',
    lenderName: 'Oom Piet Bezuidenhout',
    entityOrContact: 'Personal Account',
    emailPhone: '+27 82 333 4455',
    fundingType: 'Ad-hoc Friends & Family',
    capitalAmountZAR: 450_000,
    disbursementDate: '2026-04-01',
    maturityDate: '2027-04-01',
    returnTermsType: 'Fixed Interest',
    returnRatePercent: 11.5,
    paymentSchedule: 'At Exit (Maturity)',
    linkedDealId: undefined,
    linkedDealName: 'Liquid Operational Reserve',
    totalRepaidZAR: 0,
    status: 'Standby',
    notes: 'Pre-approved standby credit line. Unallocated facility ready to deploy for upcoming acquisitions and auction deposits.',
  },
];

export const INITIAL_SUPPLIERS: LocalSupplier[] = [
  {
    id: 'sup-1',
    name: 'Builders Warehouse Sandton',
    category: 'General Building Merchant',
    branchLocation: 'Rivonia Rd, Sandton, JHB',
    contactPerson: 'David Khumalo',
    phone: '+27 11 897 5000',
    email: 'sandton@builders.co.za',
    accountNumber: 'BW-90234',
    discountTerms: '7.5% Trade Cash & Carry / 30 Day Net',
    rating: 5,
  },
  {
    id: 'sup-2',
    name: 'Chamberlains Hardware Menlyn',
    category: 'Hardware & Timber',
    branchLocation: 'Atterbury Rd, Menlyn, Pretoria',
    contactPerson: 'Francois du Plessis',
    phone: '+27 12 348 1234',
    email: 'menlyn@chamberlains.co.za',
    accountNumber: 'CH-4512',
    discountTerms: '5% Contractor Discount',
    rating: 5,
  },
  {
    id: 'sup-3',
    name: 'Plumblink Foreshore',
    category: 'Plumbing Supplies',
    branchLocation: 'Marine Drive, Paarden Eiland, Cape Town',
    contactPerson: 'Wayne Peterson',
    phone: '+27 21 511 7788',
    email: 'capetown@plumblink.co.za',
    accountNumber: 'PL-7789',
    discountTerms: '10% on Sanitaryware & Geysers',
    rating: 4,
  },
  {
    id: 'sup-4',
    name: 'Tile Africa Centurion',
    category: 'Tiles & Sanitary',
    branchLocation: 'Old JHB Road, Centurion',
    contactPerson: 'Nomsa Sithole',
    phone: '+27 12 653 4400',
    email: 'centurion@tileafrica.co.za',
    accountNumber: 'TA-1120',
    discountTerms: '8% Bulk Porcelain Pricing',
    rating: 4,
  },
  {
    id: 'sup-5',
    name: 'Master Electricians SA',
    category: 'Specialist Contractor',
    branchLocation: 'Cape Town & Boland',
    contactPerson: 'Liam Jacobs (Wireman Licence 44021)',
    phone: '+27 82 990 1122',
    email: 'liam@masterspark.co.za',
    hasCoC: true,
    rating: 5,
  },
  {
    id: 'sup-6',
    name: 'Leroy Merlin Fourways',
    category: 'General Building Merchant',
    branchLocation: 'Witkoppen Rd, Fourways, JHB',
    phone: '+27 10 493 8000',
    email: 'fourways@leroymerlin.co.za',
    discountTerms: 'Pro Loyalty Rebate Scheme',
    rating: 4,
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'task-1',
    title: 'Lodge transfer documents with Cape Town Deeds Office',
    description: 'Ensure conveyancer STBB Cape Town submits deeds lodgement for Kloof Street property.',
    dueDate: '2026-09-22',
    priority: 'Urgent',
    status: 'In Progress',
    linkedEntity: {
      type: 'flip',
      id: 'flip-1',
      name: 'Kloof Street Heritage Redesign',
    },
    createdAt: '2026-09-10',
  },
  {
    id: 'task-2',
    title: 'Process monthly interest coupon payout to Johan Meyer',
    description: 'Pay R17,500 coupon (14% p.a. on R1.5M) for Kloof Street private loan facility.',
    dueDate: '2026-09-30',
    priority: 'High',
    status: 'Pending',
    linkedEntity: {
      type: 'funding',
      id: 'fund-1',
      name: 'Johan Meyer (Private Lender)',
    },
    createdAt: '2026-09-12',
  },
  {
    id: 'task-3',
    title: 'Inspect waterproofing certificate at Sandhurst Towers',
    description: 'Body corporate requires updated plumber certificate following pressure valve repair.',
    dueDate: '2026-09-25',
    priority: 'High',
    status: 'Pending',
    linkedEntity: {
      type: 'rental',
      id: 'rental-1',
      name: 'Sandhurst Executive Suite',
    },
    createdAt: '2026-09-14',
  },
  {
    id: 'task-4',
    title: 'Draft 60-day lease renewal notice for Priya Pillay',
    description: 'Umhlanga lease expires 30 Nov 2026. Propose standard 6.5% escalation (R16,188/mo).',
    dueDate: '2026-10-01',
    priority: 'Medium',
    status: 'Pending',
    linkedEntity: {
      type: 'rental',
      id: 'rental-2',
      name: 'Umhlanga Ridge Coastal Vista',
    },
    createdAt: '2026-09-15',
  },
  {
    id: 'task-5',
    title: 'Attend Sheriff Auction in Randburg for distressed Parkhurst asset',
    description: 'Registration fee R50k refundable deposit. Max bid threshold set at R1.85M.',
    dueDate: '2026-10-05',
    priority: 'High',
    status: 'Pending',
    linkedEntity: {
      type: 'opportunity',
      id: 'opp-1',
      name: 'Parkhurst Distressed Sheriff Auction',
    },
    createdAt: '2026-09-16',
  },
  {
    id: 'task-agm-rental-1',
    title: 'Attend Body Corporate AGM & Review Budget: Sandhurst Executive Suite',
    description: 'Scheduled Body Corporate AGM on 2026-11-12. Review audited annual financial statements, trustee election, and proposed levy escalation.',
    dueDate: '2026-10-29', // 14 days before 2026-11-12
    priority: 'High',
    status: 'Pending',
    linkedEntity: {
      type: 'rental',
      id: 'rental-1',
      name: 'Sandhurst Executive Suite',
    },
    createdAt: '2026-09-16',
  },
  {
    id: 'task-agm-rental-2',
    title: 'Attend Body Corporate AGM & Review Budget: Umhlanga Ridge Coastal Vista',
    description: 'Scheduled Body Corporate AGM on 2026-10-14. Review scheme maintenance plan, CSOS compliance, and reserve fund status.',
    dueDate: '2026-09-30', // 14 days before 2026-10-14
    priority: 'High',
    status: 'Pending',
    linkedEntity: {
      type: 'rental',
      id: 'rental-2',
      name: 'Umhlanga Ridge Coastal Vista',
    },
    createdAt: '2026-09-16',
  },
];

// Helper to create pre-calculated initial opportunities
function createSampleOpportunity(
  id: string,
  title: string,
  address: string,
  city: string,
  province: 'Gauteng' | 'Western Cape' | 'KwaZulu-Natal',
  source: any,
  purchasePrice: number,
  openMarketValue: number,
  rehabCost: number,
  monthlyRent: number,
  levies: number,
  rates: number,
  exitPrice: number,
  ltv: number,
  status: any,
  isSection13Eligible: boolean = false,
  driveVault?: any,
  amenityDistances?: {
    schools: any;
    policeStation: any;
    medicalClinic: any;
    shoppingMall: any;
  },
  propertyType: PropertyTitleType = 'Sectional Title Apartment',
  agmDate?: string,
  fundingCampaign?: {
    fundingRequiredZAR?: number;
    capitalRaisedZAR?: number;
    primaryFunderName?: string;
    primaryFunderContact?: string;
    primaryFunderType?: 'Private Lender' | 'Syndicate JV Partner' | 'Friends & Family' | 'Equity Partner';
    coFundersNotes?: string;
    promisedReturnType?: 'Fixed Interest' | 'Equity Profit Split' | 'Monthly Coupon' | 'Bullet Repayment';
    promisedReturnRatePercent?: number;
    promisedPayoutSchedule?: 'Monthly Interest' | 'Quarterly' | 'At Exit (Maturity)' | 'Bi-Annual';
    securityOffered?: string;
  },
  auctioneerCommissionZAR?: number,
  municipalArrearsZAR?: number,
  strategy: DealStrategy = 'Rental'
): OpportunityDeal {
  const depositZAR = Math.round(purchasePrice * (1 - ltv / 100));
  const costs = computeAcquisitionCosts(purchasePrice, ltv);
  const metrics = calculateDealMetrics({
    purchasePrice,
    estimatedRehabCost: rehabCost,
    monthlyRentalEstimate: monthlyRent,
    monthlyLevies: levies,
    monthlyRatesTaxes: rates,
    annualInsurance: 8_400,
    managementFeePercent: 8,
    agencyVatApplicable: true,
    vacancyRatePercent: 6,
    targetExitPrice: exitPrice,
    holdingPeriodMonths: 6,
    loanToValuePercent: ltv,
    depositZAR,
    bondLTV: ltv,
    interestRatePercent: 11.75,
    loanTermYears: 20,
    costs,
    auctioneerCommissionZAR,
    municipalArrearsZAR,
  });

  const { builtInEquityZAR, builtInEquityPercent } = computeBuiltInEquity(openMarketValue, purchasePrice);
  const amenityScorecard = computeAmenityScore(
    amenityDistances ?? {
      schools: '0-5km',
      policeStation: '0-5km',
      medicalClinic: '0-5km',
      shoppingMall: '0-5km',
    }
  );

  return {
    id,
    title,
    address,
    city,
    province,
    propertyType,
    agmDate,
    source,
    openMarketValueZAR: openMarketValue,
    purchasePrice,
    builtInEquityZAR,
    builtInEquityPercent,
    amenityScorecard,
    estimatedRehabCost: rehabCost,
    monthlyRentalEstimate: monthlyRent,
    monthlyLevies: levies,
    monthlyRatesTaxes: rates,
    annualInsurance: 8_400,
    managementFeePercent: 8,
    agencyVatApplicable: true,
    vacancyRatePercent: 6,
    targetExitPrice: exitPrice,
    holdingPeriodMonths: 6,
    strategy,
    loanToValuePercent: ltv,
    bondLTV: ltv,
    depositZAR,
    interestRatePercent: 11.75,
    loanTermYears: 20,
    annualCapitalGrowthPercent: 5.0,
    annualRentalEscalationPercent: 6.0,
    annualExpenseInflationPercent: 6.0,
    bondTermYears: 20,
    costs,
    auctioneerCommissionZAR,
    municipalArrearsZAR,
    section13sex: isSection13Eligible ? calculateSection13sex(purchasePrice, 27, true) : undefined,
    driveVault,
    grossYield: metrics.grossYield,
    capRate: metrics.capRate,
    netRoi: metrics.netRoi,
    monthlyCashFlow: metrics.monthlyCashFlow,
    initialCapitalRequired: metrics.initialCapitalRequired,
    projectedFlipNetProfit: metrics.projectedFlipNetProfit,
    projectedFlipRoi: metrics.projectedFlipRoi,
    fundingRequiredZAR: fundingCampaign?.fundingRequiredZAR,
    capitalRaisedZAR: fundingCampaign?.capitalRaisedZAR,
    primaryFunderName: fundingCampaign?.primaryFunderName,
    primaryFunderContact: fundingCampaign?.primaryFunderContact,
    primaryFunderType: fundingCampaign?.primaryFunderType,
    coFundersNotes: fundingCampaign?.coFundersNotes,
    promisedReturnType: fundingCampaign?.promisedReturnType,
    promisedReturnRatePercent: fundingCampaign?.promisedReturnRatePercent,
    promisedPayoutSchedule: fundingCampaign?.promisedPayoutSchedule,
    securityOffered: fundingCampaign?.securityOffered,
    status,
    createdAt: '2026-09-15',
  };
}

export const INITIAL_OPPORTUNITIES: OpportunityDeal[] = [
  createSampleOpportunity(
    'opp-1',
    'Parkhurst Distressed Sheriff Auction',
    '42 4th Avenue, Parkhurst',
    'Johannesburg',
    'Gauteng',
    'High-Street Auction',
    1_750_000,
    2_150_000, // Open Market Value (R400k built-in equity)
    450_000,
    22_000,
    0, // Freehold
    1_850,
    2_850_000,
    0, // Cash auction purchase
    'Due Diligence',
    false,
    {
      masterFolderUrl: 'https://1drv.ms/f/s!Parkhurst-Sheriff-Auction-Pack',
      otpDocumentUrl: 'https://1drv.ms/b/s!Conditions-Of-Sale-Sheriff-JhbNorth',
      ratesBillUrl: 'https://1drv.ms/b/s!Sec118-City-Of-Joburg-Arrears-Statement',
      titleDeedUrl: 'https://1drv.ms/b/s!Parkhurst-SG-Diagram-Erf42',
    },
    {
      schools: '0-5km',
      policeStation: '0-5km',
      medicalClinic: '0-5km',
      shoppingMall: '0-5km',
    },
    'Freehold House',
    undefined,
    {
      fundingRequiredZAR: 1_600_000,
      capitalRaisedZAR: 0,
      promisedReturnType: 'Fixed Interest',
      promisedReturnRatePercent: 14.5,
      promisedPayoutSchedule: 'Monthly Interest',
      securityOffered: '2nd Mortgage Bond registered over title deed',
    },
    201_250, // Auctioneer commission (10% + 15% VAT on R1.75M)
    45_000,  // Municipal Section 118 clearance arrears
    'Flip'   // Strategy
  ),
  createSampleOpportunity(
    'opp-2',
    'Greencreek Riverwalk Developer Unit',
    'Greencreek Estate, Pretoria East',
    'Pretoria',
    'Gauteng',
    'iGrow Rentals',
    899_000,
    1_050_000, // Open Market Value (R151k built-in equity)
    0, // Brand new
    8_500,
    950,
    650,
    1_150_000,
    90,
    'Screening',
    true, // Section 13sex Eligible (Off-plan developer unit)
    {
      masterFolderUrl: 'https://drive.google.com/drive/folders/greencreek-developer-unit',
      otpDocumentUrl: 'https://drive.google.com/file/d/greencreek-dev-contract/view',
    },
    {
      schools: '0-5km',
      policeStation: '6-10km',
      medicalClinic: '6-10km',
      shoppingMall: '0-5km',
    },
    'Sectional Title Apartment',
    '2026-11-28',
    undefined,
    undefined,
    undefined,
    'Rental'
  ),
  createSampleOpportunity(
    'opp-3',
    'Bree Street City Bowl Studio',
    '155 Bree Street, CBD',
    'Cape Town',
    'Western Cape',
    'Private Agent',
    1_850_000,
    2_250_000, // Open Market Value (R400k built-in equity)
    120_000,
    17_500,
    2_100,
    1_250,
    2_450_000,
    80,
    'Offer Submitted',
    false,
    undefined,
    {
      schools: '0-5km',
      policeStation: '0-5km',
      medicalClinic: '0-5km',
      shoppingMall: '0-5km',
    },
    'Sectional Title Apartment',
    '2027-01-20',
    undefined,
    undefined,
    undefined,
    'Rental'
  ),
];

export const INITIAL_INVESTOR_PROFILE: InvestorProfile = {
  entityName: 'L&M Property Investments (Pty) Ltd',
  tradingAs: 'L&M Trading & Capital',
  registrationOrId: '2022/498211/07',
  contactNumber: '+27 82 890 4321',
  email: 'invest@lmtrading.co.za',
  website: 'www.lmtrading.co.za',
  physicalAddress: 'Suite 402, The Boulevard Office Park, Cape Town',
  logoBase64: '',
  bioSummary: 'Sole proprietor and syndication vehicle focusing on distressed residential asset acquisition, light-industrial repositioning, and high-yield sectional title developments across the Western Cape and Gauteng corridors.',
  defaultPrimeRatePercent: 11.75,
  baselineHurdleYieldPercent: 10.0,
  defaultAgentCommissionPercent: 5.0,
};

export const INITIAL_ANALYZER_DRAFT: AnalyzerDraft = {
  strategy: 'Rental',
  openMarketValue: 2_150_000,
  purchasePrice: 1_800_000,
  rehabCost: 200_000,
  monthlyRent: 16_500,
  monthlyLevies: 1_650,
  monthlyRates: 1_100,
  targetExitPrice: 2_450_000,
  auctioneerCommission: 0,
  municipalArrears: 0,
  depositZAR: 0,
  loanToValue: 100,
  annualCapitalGrowthPercent: 5.0,
  annualRentalEscalationPercent: 6.0,
  annualExpenseInflationPercent: 6.0,
  bondTermYears: 20,
  source: 'High-Street Auction',
  vacancyRatePercent: 6.0,
  managementFeePercent: 8.0,
  agencyVatApplicable: true,
};

export const EMPTY_ANALYZER_DRAFT: AnalyzerDraft = {
  strategy: 'Rental',
  openMarketValue: 0,
  purchasePrice: 0,
  rehabCost: 0,
  monthlyRent: 0,
  monthlyLevies: 0,
  monthlyRates: 0,
  targetExitPrice: 0,
  auctioneerCommission: 0,
  municipalArrears: 0,
  depositZAR: 0,
  loanToValue: 0,
  annualCapitalGrowthPercent: 5.0,
  annualRentalEscalationPercent: 6.0,
  annualExpenseInflationPercent: 6.0,
  bondTermYears: 20,
  source: 'High-Street Auction',
  vacancyRatePercent: 6.0,
  managementFeePercent: 8.0,
  agencyVatApplicable: true,
};

export const DEFAULT_AI_SETTINGS: AiSettings = {
  provider: 'anthropic',
  apiKey: '',
  model: 'claude-sonnet-5',
};

